# SPDX-License-Identifier: MulanPSL-2.0
"""Primitive-backed hand adapter for the hand_gesture skill.

The dance loop (``main.py``) is written against a single SDK-shaped ``hand``
handle. Instead of opening the CAN bus directly, this module exposes a
look-alike adapter that routes every hand call through the robonix d1_hand
*primitive* over gRPC. The skill is thus a pure consumer; the primitive owns
the hardware.

Mapping (only the methods the dance loop actually calls):

  hand.set_joint_pos(vec)   -> hand/move_joint (named JointValue[], [0,1])
  hand.open_hand()          -> hand/move_joint all-open (safe rest pose)

``axis_names`` comes from ``hand/info`` in the primitive's axis order (the same
DexHand.joint_names order the SDK uses: thumb_cmc_pitch .. pinky_mcp_pitch), so
a 6-vector built for the DexHand maps index-for-index onto the primitive.
"""
from __future__ import annotations


class PrimitiveHand:
    """DexHand-look-alike backed by the hand primitive (normalized [0,1])."""

    def __init__(self, *, move_joint_stub, hand_pb2, axis_names) -> None:
        self._mj = move_joint_stub
        self._pb = hand_pb2
        self._names = list(axis_names)

    @property
    def num_joints(self) -> int:
        return len(self._names)

    def set_joint_pos(self, vec) -> None:
        vec = [float(v) for v in vec]
        if len(vec) != len(self._names):
            raise ValueError(f"expected {len(self._names)} hand values, got {len(vec)}")
        targets = [self._pb.JointValue(name=n, value=v) for n, v in zip(self._names, vec)]
        resp = self._mj.MoveJoint(self._pb.MoveJoint_Request(targets=targets))
        if not resp.ok:
            raise RuntimeError(f"hand move_joint failed: {resp.message}")

    def open_hand(self) -> None:
        # Safe rest: fully open (all axes 0.0).
        self.set_joint_pos([0.0] * len(self._names))


def connect_primitives(skill):
    """Discover + connect the d1_hand primitive via atlas and return a
    ``PrimitiveHand`` adapter. Raises RuntimeError if the primitive is not
    registered / reachable. Channels are tracked by ``skill`` and closed on
    teardown."""
    import grpc
    from robonix_api import ATLAS
    from robonix_api.atlas_types import Transport

    # Generated by rbnx codegen into rbnx-build/codegen/proto_gen (added to
    # sys.path by the Skill constructor before this module is imported).
    import hand_pb2  # type: ignore
    import robonix_contracts_pb2_grpc as cg  # type: ignore

    def _stub(contract: str, stub_cls):
        caps = ATLAS.find_capability(contract_id=contract, transport=Transport.GRPC)
        if not caps:
            raise RuntimeError(
                f"no gRPC provider for {contract} — is the primitive deployed and running?"
            )
        ch = skill.connect_capability(caps[0], contract, Transport.GRPC)
        return stub_cls(grpc.insecure_channel(ch.endpoint))

    info = _stub("robonix/primitive/hand/info", cg.RobonixPrimitiveHandInfoStub).GetHandInfo(
        hand_pb2.GetHandInfo_Request()
    )
    if not info.ok:
        raise RuntimeError(f"hand info failed: {info.message}")

    return PrimitiveHand(
        move_joint_stub=_stub("robonix/primitive/hand/move_joint", cg.RobonixPrimitiveHandMoveJointStub),
        hand_pb2=hand_pb2,
        axis_names=[j.name for j in info.joints],
    )
