#!/usr/bin/env python3
# SPDX-License-Identifier: MulanPSL-2.0
"""D1 head camera primitive — Intel RealSense D435i, direct (non-ROS) backend.

Owns robonix/primitive/camera/* for the D1's head-mounted RealSense. The D1
robonix deployment has no ROS backend, so this exposes only the on-demand
rpc/MCP snapshot contracts (not the rgb/depth/intrinsics topic_out streams):

  robonix/primitive/camera/snapshot        rpc (gRPC) one RGB frame as JPEG Image
  robonix/primitive/camera/depth_snapshot  rpc (MCP)  one depth frame, normalized JPEG
  robonix/primitive/camera/driver          rpc        lifecycle (wired to on_init)

Wraps vision.RealSenseCamera (pyrealsense2) from the Beingbeyond_D1 repo.
Resolution / frame come from primitive config or D1_CAMERA_* env vars.
"""
from __future__ import annotations

import os
import sys
import threading
import time
from io import BytesIO

import numpy as np

from robonix_api import Primitive, Ok, Err

# Make the Beingbeyond_D1 repo importable (vision.py lives at the repo root).
_ROOT = os.environ.get("BEINGBEYOND_PATH", os.path.expanduser("~/Beingbeyond_D1"))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

d1_camera = Primitive(id="d1_camera", namespace="robonix/primitive/camera")

# codegen MCP dataclasses — generated by scripts/build.sh into
# rbnx-build/codegen/robonix_mcp_types, which the Primitive constructor adds
# to sys.path itself.
import builtin_interfaces_mcp        # noqa: E402
import std_msgs_mcp                  # noqa: E402
from sensor_msgs_mcp import Image    # noqa: E402
from std_msgs_mcp import Empty       # noqa: E402

# gRPC codegen products (same proto_gen dir) — snapshot is served over gRPC so
# programmatic consumers (e.g. the block_grasp skill) get a synchronous
# sensor_msgs/Image without an MCP client. depth_snapshot stays MCP below.
import builtin_interfaces_pb2        # noqa: E402
import camera_pb2                    # noqa: E402
import sensor_msgs_pb2               # noqa: E402
import std_msgs_pb2                  # noqa: E402

# ── shared state ──────────────────────────────────────────────────────────────
_camera = None
_lock = threading.Lock()
_frame_id = "camera"


# ── image conversion ──────────────────────────────────────────────────────────
def _now_header(frame_id: str) -> "std_msgs_mcp.Header":
    now = time.time()
    return std_msgs_mcp.Header(
        stamp=builtin_interfaces_mcp.Time(
            sec=int(now), nanosec=int((now % 1) * 1e9) % 1_000_000_000
        ),
        frame_id=frame_id,
    )


def _rgb_to_image_mcp(rgb: np.ndarray, frame_id: str) -> Image:
    """Encode an RGB uint8 (H, W, 3) array as a JPEG sensor_msgs/Image."""
    from PIL import Image as PILImage

    buf = BytesIO()
    PILImage.fromarray(np.ascontiguousarray(rgb)).save(buf, format="JPEG", quality=85)
    jpg = buf.getvalue()
    h, w = rgb.shape[:2]
    return Image(
        header=_now_header(frame_id),
        height=h,
        width=w,
        encoding="jpeg",
        is_bigendian=0,
        step=len(jpg),
        data=jpg,
    )


def _depth_to_image_mcp(depth_m: np.ndarray, frame_id: str) -> Image:
    """Normalize a float32 depth (metres) frame to 8-bit grayscale JPEG."""
    valid = np.isfinite(depth_m) & (depth_m > 0)
    if valid.any():
        mn, mx = depth_m[valid].min(), depth_m[valid].max()
        norm = np.where(
            valid, (depth_m - mn) / max(mx - mn, 1e-6) * 255, 0
        ).astype(np.uint8)
    else:
        norm = np.zeros(depth_m.shape, np.uint8)
    gray = np.stack([norm, norm, norm], axis=-1)
    return _rgb_to_image_mcp(gray, frame_id)


def _rgb_to_image_pb2(rgb: np.ndarray, frame_id: str) -> "sensor_msgs_pb2.Image":
    """Encode an RGB uint8 (H, W, 3) array as a JPEG sensor_msgs/Image (pb2)."""
    from PIL import Image as PILImage

    buf = BytesIO()
    PILImage.fromarray(np.ascontiguousarray(rgb)).save(buf, format="JPEG", quality=85)
    jpg = buf.getvalue()
    h, w = rgb.shape[:2]
    now = time.time()
    return sensor_msgs_pb2.Image(
        header=std_msgs_pb2.Header(
            stamp=builtin_interfaces_pb2.Time(
                sec=int(now), nanosec=int((now % 1) * 1e9) % 1_000_000_000
            ),
            frame_id=frame_id,
        ),
        height=h,
        width=w,
        encoding="jpeg",
        is_bigendian=0,
        step=len(jpg),
        data=jpg,
    )


# ── snapshot (gRPC) + depth_snapshot (MCP) ──────────────────────────────────────
@d1_camera.grpc("robonix/primitive/camera/snapshot")
def snapshot(request, context):
    """拍一张头部相机 RGB 图（按需单帧），返回 JPEG 编码的 sensor_msgs/Image。
    Served over gRPC for synchronous programmatic consumers.
    Contract: robonix/primitive/camera/snapshot."""
    _ = request, context
    with _lock:
        cam = _camera
    if cam is None:
        return camera_pb2.GetCameraImage_Response()
    rgb, _depth = cam.get_aligned_frames(filtered=False)
    return camera_pb2.GetCameraImage_Response(image=_rgb_to_image_pb2(rgb, _frame_id))


@d1_camera.mcp("robonix/primitive/camera/depth_snapshot")
def depth_snapshot(msg: Empty) -> Image:
    """拍一张头部相机深度图（归一化到 8-bit 灰度的 JPEG，data 为 base64）。
    Contract: robonix/primitive/camera/depth_snapshot."""
    _ = msg
    with _lock:
        cam = _camera
    if cam is None:
        raise RuntimeError("camera not initialized")
    _rgb, depth_m = cam.get_aligned_frames(filtered=True)
    return _depth_to_image_mcp(depth_m, _frame_id)


# ── lifecycle ─────────────────────────────────────────────────────────────────
@d1_camera.on_init
def init(cfg):
    """Open the RealSense at the configured resolution and confirm one frame
    before declaring ready. Config keys (fall back to D1_CAMERA_* env):
    width, height, fps, frame_id."""
    global _camera, _frame_id
    cfg = cfg or {}
    width = int(cfg.get("width") or os.environ.get("D1_CAMERA_WIDTH", "1280"))
    height = int(cfg.get("height") or os.environ.get("D1_CAMERA_HEIGHT", "720"))
    fps = int(cfg.get("fps") or os.environ.get("D1_CAMERA_FPS", "30"))
    _frame_id = cfg.get("frame_id") or os.environ.get("D1_CAMERA_FRAME_ID", "camera")

    try:
        from vision import RealSenseCamera
    except Exception as exc:  # noqa: BLE001
        return Err(f"import RealSenseCamera failed (BEINGBEYOND_PATH={_ROOT}): {exc}")

    try:
        cam = RealSenseCamera(width=width, height=height, hz=fps)
        cam.get_aligned_frames(filtered=False)  # confirm the stream delivers a frame
    except Exception as exc:  # noqa: BLE001
        return Err(f"open RealSense failed: {exc}")

    with _lock:
        _camera = cam
    print(f"[d1_camera] ready: {width}x{height}@{fps} frame_id={_frame_id}", flush=True)
    return Ok()


@d1_camera.on_shutdown
def shutdown():
    global _camera
    with _lock:
        cam, _camera = _camera, None
    if cam is not None:
        try:
            cam.stop()
        except Exception:  # noqa: BLE001
            pass
    return Ok()


def main() -> int:
    d1_camera.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
