#!/usr/bin/env python3
# SPDX-License-Identifier: MulanPSL-2.0
"""D1 arm primitive — 6-DOF arm over the HeadArm serial link, direct (non-ROS).

Owns the robonix/primitive/arm/* contracts, served over gRPC:

  robonix/primitive/arm/driver      rpc   lifecycle (via on_init)
  robonix/primitive/arm/info        rpc   joint names / count / model
  robonix/primitive/arm/move_joint  rpc   set arm joint positions (rad, absolute)
  robonix/primitive/arm/get_state   rpc   read arm joint positions + velocities (rad)
  robonix/primitive/arm/move_pose   rpc   Cartesian EE pose (xyz + rpy) via SDK IK
  robonix/primitive/arm/set_head    rpc   set the 2 head joints (yaw,pitch), block until reached

Wraps beingbeyond_d1_sdk.head_arm.HeadArmRobot directly for the joint interface
and beingbeyond_d1_sdk.pin_kinematics.D1Kinematics for move_pose's inverse
kinematics. Joint values are absolute radians (unlike the hand's normalized
[0,1]).

The HeadArm chain is 8 joints: [0]=joint_7_head_yaw, [1]=joint_8_head_pitch,
[2..7]=joint_1..joint_6. This primitive exposes the 6 arm joints for motion; the
2 head joints share the same serial link and are read + held at their current
pose on every arm command. Head positioning is offered separately via set_head
(there is no standalone head primitive — the serial link is owned here).

Not provided: state_joint (topic_out — needs a ROS backend the D1 deploy does
not run; replaced here by the get_state rpc).
"""
from __future__ import annotations

import math
import os
import threading

from robonix_api import Primitive, Ok, Err

d1_arm = Primitive(id="d1_arm", namespace="robonix/primitive/arm")

# codegen products (generated by scripts/build.sh into rbnx-build/codegen/
# proto_gen, auto-added to sys.path by the Primitive constructor).
import arm_pb2  # type: ignore[import-not-found]  # noqa: E402

# HeadArm SDK joint layout (8 total, hardware order):
#   [0] joint_7_head_yaw   [1] joint_8_head_pitch   <- head (held, not exposed)
#   [2] joint_1 .. [7] joint_6                       <- arm (exposed)
_ARM_START = 2
_ARM_COUNT = 6

# ── shared state ──────────────────────────────────────────────────────────────
_robot = None   # HeadArmRobot
_kin = None     # D1Kinematics (for move_pose IK)
_lock = threading.Lock()   # serialize serial-link access across handlers
_arm_joint_names: list[str] = []
_model = "beingbeyond_d1_arm"
# Max acceptable IK position error (m) before move_pose rejects the solution.
_ik_pos_tol = 0.05


# ── gRPC handlers ─────────────────────────────────────────────────────────────
@d1_arm.grpc("robonix/primitive/arm/info")
def info(request, context):
    """Query the arm's joint names (arm only), count, and model tag.
    Contract: robonix/primitive/arm/info."""
    _ = request, context
    if _robot is None:
        return arm_pb2.GetArmInfo_Response(
            ok=False, message="arm not initialized — Driver(CMD_INIT) failed or never ran"
        )
    return arm_pb2.GetArmInfo_Response(
        ok=True,
        message="",
        joint_names=list(_arm_joint_names),
        num_joints=_ARM_COUNT,
        model=_model,
    )


@d1_arm.grpc("robonix/primitive/arm/move_joint")
def move_joint(request, context):
    """Set all arm joints to absolute positions (radians), in info.joint_names
    order. Head joints are read and held. Rejects (never truncates/clamps) wrong
    length or non-finite values. ok=true = accepted & dispatched, NOT reached.
    Contract: robonix/primitive/arm/move_joint."""
    _ = context
    positions = list(request.positions)
    if len(positions) != _ARM_COUNT:
        return arm_pb2.MoveJoint_Response(
            ok=False,
            message=f"expected {_ARM_COUNT} joint values, got {len(positions)}",
        )
    for i, v in enumerate(positions):
        if not math.isfinite(v):
            return arm_pb2.MoveJoint_Response(
                ok=False, message=f"non-finite value at index {i}: {v}"
            )
    with _lock:
        robot = _robot
        if robot is None:
            return arm_pb2.MoveJoint_Response(ok=False, message="arm not initialized")
        try:
            full = list(robot.get_positions())  # 8-vector, head + arm
            full[_ARM_START:_ARM_START + _ARM_COUNT] = [float(v) for v in positions]
            robot.set_positions(full)
        except Exception as exc:  # noqa: BLE001
            return arm_pb2.MoveJoint_Response(ok=False, message=f"set_positions failed: {exc}")
    return arm_pb2.MoveJoint_Response(ok=True, message="")


@d1_arm.grpc("robonix/primitive/arm/get_state")
def get_state(request, context):
    """Read current arm joint positions + velocities (rad, rad/s), in
    info.joint_names order. Contract: robonix/primitive/arm/get_state."""
    _ = request, context
    with _lock:
        robot = _robot
        if robot is None:
            return arm_pb2.GetJointState_Response(ok=False, message="arm not initialized")
        try:
            pos, vel = robot.get_positions_and_velocities()  # 8-vectors
        except Exception as exc:  # noqa: BLE001
            return arm_pb2.GetJointState_Response(ok=False, message=f"read state failed: {exc}")
    sl = slice(_ARM_START, _ARM_START + _ARM_COUNT)
    return arm_pb2.GetJointState_Response(
        ok=True,
        message="",
        positions=[float(v) for v in pos[sl]],
        velocities=[float(v) for v in vel[sl]],
    )


@d1_arm.grpc("robonix/primitive/arm/move_pose")
def move_pose(request, context):
    """Move the end-effector to a Cartesian pose (base frame) via the SDK's
    arm-only IK; head joints are held. Position in metres, orientation in
    roll/pitch/yaw radians (XYZ-euler). ok=false on IK failure / out of reach.
    Contract: robonix/primitive/arm/move_pose."""
    _ = context
    import numpy as np
    from scipy.spatial.transform import Rotation as R

    vals = [request.x, request.y, request.z, request.roll, request.pitch, request.yaw]
    if not all(math.isfinite(v) for v in vals):
        return arm_pb2.MovePose_Response(ok=False, message=f"non-finite pose value: {vals}")

    with _lock:
        robot, kin = _robot, _kin
        if robot is None or kin is None:
            return arm_pb2.MovePose_Response(ok=False, message="arm not initialized")
        try:
            q_full = np.asarray(robot.get_positions(), dtype=float)
            q_head, q_arm = kin.split_q(q_full)

            T = np.eye(4)
            T[:3, :3] = R.from_euler(
                "xyz", [request.roll, request.pitch, request.yaw]
            ).as_matrix()
            T[:3, 3] = [request.x, request.y, request.z]

            _q_hs, q_as, err, _iters = kin.ik_T_ee_with_arm_only(T, q_head, q_arm)
        except Exception as exc:  # noqa: BLE001
            return arm_pb2.MovePose_Response(ok=False, message=f"IK failed: {exc}")

        if not math.isfinite(err) or err > _ik_pos_tol:
            return arm_pb2.MovePose_Response(
                ok=False,
                message=f"no IK solution within tolerance: err={err:.4f} m "
                f"(tol={_ik_pos_tol:.4f})",
                position_error=float(err) if math.isfinite(err) else 0.0,
            )

        try:
            cmd = np.concatenate([q_head, q_as])  # hold head at current pose
            robot.set_positions(cmd)
        except Exception as exc:  # noqa: BLE001
            return arm_pb2.MovePose_Response(ok=False, message=f"set_positions failed: {exc}")

    return arm_pb2.MovePose_Response(
        ok=True,
        message="",
        position_error=float(err),
        arm_solution=[float(v) for v in q_as],
    )


@d1_arm.grpc("robonix/primitive/arm/set_head")
def set_head(request, context):
    """Set the 2 head joints (yaw, pitch) to absolute radians and block until
    reached; the 6 arm joints are held at their current pose. Rejects non-finite
    values. ok=true = reached. Contract: robonix/primitive/arm/set_head."""
    _ = context
    yaw, pitch = request.yaw, request.pitch
    if not (math.isfinite(yaw) and math.isfinite(pitch)):
        return arm_pb2.SetHead_Response(
            ok=False, message=f"non-finite head angle: yaw={yaw} pitch={pitch}"
        )
    with _lock:
        robot = _robot
        if robot is None:
            return arm_pb2.SetHead_Response(ok=False, message="arm not initialized")
        try:
            full = list(robot.get_positions())  # 8-vector, head + arm
            full[0] = float(yaw)    # joint_7_head_yaw
            full[1] = float(pitch)  # joint_8_head_pitch
            robot.set_positions(full)
            robot.wait_until_reached(full, active_joint_indices=[0, 1])
        except Exception as exc:  # noqa: BLE001
            return arm_pb2.SetHead_Response(ok=False, message=f"set head failed: {exc}")
    return arm_pb2.SetHead_Response(ok=True, message="")


# ── lifecycle ─────────────────────────────────────────────────────────────────
@d1_arm.on_init
def init(cfg):
    """Open the HeadArm serial link + set up kinematics for move_pose. Config
    keys (fall back to D1_ARM_* env): dev, baudrate, urdf_path, ik_pos_tol."""
    global _robot, _kin, _arm_joint_names, _ik_pos_tol
    cfg = cfg or {}
    dev = str(cfg.get("dev") or os.environ.get("D1_ARM_DEV", "/dev/ttyUSB0"))
    baudrate = int(cfg.get("baudrate") or os.environ.get("D1_ARM_BAUD", "1000000"))
    urdf_path = str(cfg.get("urdf_path") or os.environ.get("D1_ARM_URDF", ""))
    _ik_pos_tol = float(cfg.get("ik_pos_tol") or os.environ.get("D1_ARM_IK_POS_TOL", "0.05"))

    try:
        from beingbeyond_d1_sdk.head_arm import HeadArmRobot
        from beingbeyond_d1_sdk.pin_kinematics import D1Kinematics, D1KinematicsConfig
        if not urdf_path:
            from beingbeyond_d1_sdk.urdf_path import get_default_urdf_path
            urdf_path = get_default_urdf_path()
    except Exception as exc:  # noqa: BLE001
        return Err(f"import beingbeyond_d1_sdk failed: {exc}")

    try:
        robot = HeadArmRobot(urdf_path=urdf_path, dev=dev, baudrate=baudrate)
        names = list(robot.joint_names)
        kin = D1Kinematics(D1KinematicsConfig(urdf_path=urdf_path))
    except Exception as exc:  # noqa: BLE001
        return Err(f"open HeadArm (dev={dev}) failed: {exc}")

    with _lock:
        _robot = robot
        _kin = kin
        _arm_joint_names = names[_ARM_START:_ARM_START + _ARM_COUNT]
    print(f"[d1_arm] ready: dev={dev} joints={_arm_joint_names} "
          f"ik_pos_tol={_ik_pos_tol}", flush=True)
    return Ok()


@d1_arm.on_shutdown
def shutdown():
    """Home the head-arm chain and release the serial link."""
    global _robot, _kin
    with _lock:
        robot, _robot = _robot, None
        _kin = None
    if robot is not None:
        try:
            robot.close()
        except Exception:  # noqa: BLE001
            pass
    return Ok()


def main() -> int:
    d1_arm.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
